### ISSUE TITLE
Templates based MIA

### ISSUE THREAD

**Issue by SchnWalter** [patcon/mission-impossible-android#30]
I've created a [branch](https://github.com/SchnWalter/mission-impossible-android/tree/templates) on which I've started up change MIA (or however you want to call it) in order to make use of template files so that one can build various update.zip files depending on the needs...

On my opinion there should be a minimal template that should include some
* Cal/CardDav for contancts/calendar.
* email client
* a web browser
* security related apps

For this template would like to suggest DAVdroid, K-9 Mail and the stripped down version of FF (Fennec FDroid) -- *but I'm not sure how secure the apps are and whether or not there was a security audit on those apps*

Am I missing something that someone would want on a minimal "working" and "secure" system? (maybe maps?!? - after all it's a smartphone)

Then have a default template which might look more or less like the current list of apps.

And maybe also implement a way to remove apps out of the original CM build. What do you think?

And for the workflow of using these templates I was thinking something on the lines of [weevee](https://github.com/jedi4ever/veewee) (but in python3)

Basically instead of the current `make` workflow you would have a tool that you could run anywhere onto your system and you would do something like this:
```
mia definition --template=minimal my-tablet-image
# configure the settings.ini
mia build my-tablet-image
mia install my-tablet-image
```
Where `mia` would be the name of the script and the first parameter the command name.

The first step would generate a definition folder which would basically be a copy of the template that you could then configure to your liking or just go with the defaults.
After the configurations were made you could then build/create a update.zip file. and the last one would push that file to your attached device.

Then in the same folder you could work on a template for a different device
```
mia definition --template=default my-nexus-phone
mia build my-nexus-phone
mia install my-nexus-phone
```
And then you could just archive the definitions and keep them for the next time you want to reset your phone/tablet. Or just delete it and use a new fresh template.

Someone would need to compile a list of trustworthy apps... and... I'm opting out of this! :D

I've already played with command line arguments and I'm confident I can make the scripts, just need some suggestions. And I'm going to ditch Bash... and use it only where it is really necessary.

**Comment by patcon** [comment]
Yay! I really like all of this @SchnWalter!

A maps app seems sensible. I'm thinking too much discussion over the app selection might be premature at this point, but I like the idea of scripts to make it simpler to customize. I'm sympathetic if you feel we threw too much in right now and its bloated, but as of right now, there are only a few of us using it, so for me at least, I was ok with adding anything any of us wanted in there :) Didn't seem worth being exclusive yet.

More specific comments forthcoming when I've had time to review your PR

As for contacts, I'm expecting to use Flock once someone has time to create a desktop encryption proxy. It's a really user-friendly option for syncing contacts/calendar, aside from the "only works on Android" thing that it has going on right now.
https://github.com/WhisperSystems/Flock/issues/16

**Comment by patcon** [comment]
Oh also, Mike rightfully suggested that we should rebrand one browser as "unsafe":
https://github.com/patcon/mission-impossible-android/issues/5#issuecomment-75457505

The idea is that, to protect users like Tails OS does, the browser authorized for captive portal use should not be the main browser.

**Comment by SchnWalter** [comment]
I have updated the `make` file to work with templates, and i've tested things up until pushing the zip files to the phone: https://github.com/SchnWalter/mission-impossible-android/tree/templates

And I want to make sure that it is still respecting the guidelines from the Tor blog post. If you could please give it a try because I'm going to fork that branch and I will start working on a set of python scripts to replace the horrible make file and bash scripts.

I will add a `tools/mia` python script and a `mia` folder (with custom python modules) in the root of the project and I will try to make the files as simple as possible so that it will be easy to audit the code.

And I'm also going to add a `lib` folder with [docopt](https://github.com/docopt/docopt) for proccessing the CLI arguments.

**Comment by SchnWalter** [comment]
I've been playing around with python3 these days...

Here's a basic CLI tool: https://github.com/SchnWalter/mission-impossible-android/tree/python-tools

For now it only has a simple command to generate definitions... using the same template as the previous bash implementention; but with YAML instead of INI files. This way we can also add checksums (#31). And I've re-added the lock file, but I'm not sure if it is really needed since the python implementation of xpath is very fast.

I'm going to gradually remove Bash code once the similar functionality is implemented in the Python scripts.

P.S. I'm not python programmer; Feel free to sugest a ton changes in the code!

**Comment by patcon** [comment]
Just to make sure you're not waiting on me, don't forget to submit a PR when you're ready to submit. As I said, the sooner the better -- would be great to get something in from this large task, feature-complete or not, and perhaps preferably not :)

Thanks for your enthusiasm on this Schneider!

**Comment by mikeperry-tor** [comment]
I think this is merged and done now? Closing.
