### ISSUE TITLE
Disable `adb push` progress bar for versions < 1.0.32

### ISSUE THREAD

**Issue by patcon** [patcon/mission-impossible-android#32]
Reported by @mikeperry-tor in IRC.

**Comment by patcon** [comment]
For context, we get progress bars fro free in adb 1.0.32, but as of right now, only 1.0.31 is in the debian package that provides adb.

**Comment by SchnWalter** [comment]
Done: https://github.com/SchnWalter/mission-impossible-android/commit/136c5beb41f8764bb5dba2fc50977786d0512804

**Comment by mikeperry-tor** [comment]
Ok, closing this.
